# -*- coding: utf-8 -*-
"""Assesement1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HXqlZsSO1tHMQ05Dhjmw_N0oZdrW-69B
"""

value1=float(input("Enter the first number : "))
value2=float(input("Enter the second number : "))
value3=float(input("Enter the third number : ")) 
value4=float(input("Enter the forth number : "))

plus_multiplication_symbol=input("Enter either a plus sign '+' or a multiplication sign '*': ")
 
if plus_multiplication_symbol=='+':
    
    sum_of_all_values=value1+value2+value3+value4
     
    print("The sum of all four numbers: {:.3f}".format(sum_of_all_values))
elif plus_multiplication_symbol=='*':
    
    product_of_all_values=value1*value2*value3*value4
     
    print("The product of all four numbers: {:.3f}".format(product_of_all_values))
else:
    print("Error. Please enter only plus (+) or multiplication (*) sign.")