# -*- coding: utf-8 -*-
"""Generate randint

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FvFgiLvPNAKgXmc6pZv6mH20w4tTpl6g
"""

import random
print(random.randint(1,101))

# create list
mylist = []  

# generate random number between 1 and 100
for e in range(50):
     e = random.randrange(1,100)  
     mylist.append(e)  # add to list
     

# search / collect input 
num = int(input("Please enter a number between 1 and 100: "))   

# check if number is in list
if i in list:  
    for i in list:
        print(i,end=" ")
           
else:
    print("Error. The number is not in the list.")

